import test from "node:test";
import assert from "node:assert/strict";
import {calculateAppearance,calculateCardEV} from "../app.mjs";
import {GRAND_LIVE_RUN,calculateCareerProjection} from "../career.mjs";
const card={id:99999,type:0,rarity:3,specialty_rate:80,unique_specialty:1.2,fs_specialty:1,tb:1.15,mb:1.3,fs_bonus:1.2,unique_fs_bonus:1,stat_bonus:[1,0,0,0,0,0],fs_stats:[0,0,0,0,0,0],fs_training:0,fs_motivation:0,fs_ramp:[0,0],sb:35,offstat_appearance_denominator:4,event_stats:[20,0,10,0,0,30,0,10]};
test("appearance formula reproduces Euophrys Kitasan example",()=>{const r=calculateAppearance(card,0);assert.equal(r.specialtyWeight,216);assert.ok(Math.abs(r.specialty-216/666)<1e-12)});
test("global specialty priority raises preferred appearance and lowers each off-type appearance",()=>{const a=calculateAppearance(card,0),b=calculateAppearance(card,20);assert.ok(b.specialty>a.specialty);assert.ok(b.eachOff<a.eachOff)});
test("appearance probabilities sum to one",()=>{const r=calculateAppearance(card,20);assert.ok(Math.abs(r.specialty+r.eachOff*4+r.none-1)<1e-12)});
test("card EV returns positive specialty output",()=>{const r=calculateCardEV(card,{globalSpecialty:20,profile:"gl-late",motivation:.2,growth:[1,1,1,1,1,1],spWeight:1});assert.ok(r.rainbowScore>0);assert.ok(r.allPlacementScore>=r.specialtyScore)});
test("career projection splits Grand Live into bond and rainbow phases",()=>{const r=calculateCareerProjection(card,{globalSpecialty:20});assert.equal(r.daysToBond+r.rainbowDays,GRAND_LIVE_RUN.trainingTurns);assert.ok(r.rainbowDays>0);assert.ok(r.rainbowClicks>0);assert.ok(r.vector.some(v=>v>0))});
test("starting and event bond bring a card online earlier",()=>{const low=calculateCareerProjection({...card,sb:0,event_stats:[0,0,0,0,0,0,0,0]});const high=calculateCareerProjection({...card,sb:45,event_stats:[0,0,0,0,0,0,0,20]});assert.ok(high.daysToBond<low.daysToBond);assert.ok(high.rainbowDays>low.rainbowDays)});
